### ISSUE TITLE
It's not returning anything on cache hits

### ISSUE THREAD

**Issue by simoheinonen** [Lustmored/flysystem-v2-simple-cache-adapter#5]
Not sure if I'm misunderstanding something but to me it looks like it's not working at all.

The items are saved to cache but the saved content is never read. For example in `read()` it first gets the cache item and then always goes for the adapter regardless if the cache item was hit or miss

https://github.com/Lustmored/flysystem-v2-simple-cache-adapter/blob/main/src/CacheAdapter.php#L93-L97

**Comment by Lustmored** [comment]
This adapter does not store file contents in cache, just metadata. Therefore `read` method has to call adapter every time.

**Comment by simoheinonen** [comment]
Oh okay. Just curious, what's the use case for that?
